0.12.2 - publish to npm with provenance, run 2 separate publish jobs after build success

diff --git a/.github/workflows/build-and-publish-components-pkg.yml b/.github/workflows/build-and-publish-components-pkg.yml
--- a/.github/workflows/build-and-publish-components-pkg.yml
+++ b/.github/workflows/build-and-publish-components-pkg.yml
@@ -5,15 +5,12 @@ on:
     branches:
       - main
 
-permissions:
-  packages: write
-
 env:
   BUN_VERSION: 1.3.1
 
 jobs:
-  build-and-publish-components:
-    name: "Build & publish @schemavaults/ui React components package"
+  Build:
+    name: "Build @schemavaults/ui React components package"
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -22,6 +19,8 @@ jobs:
         uses: oven-sh/setup-bun@v2
         with:
           bun-version: ${{ env.BUN_VERSION }}
+      - name: Configure bun to install from GitHub Packages
+        run: rm -rf .npmrc
       - name: Install dependencies with Bun
         run: bun install
         env:
@@ -31,6 +30,34 @@ jobs:
         run: bun run lint
       - name: Build package with Bun
         run: bun run build
+      - name: Pack up package with Bun
+        run: bun pm pack --quiet --filename schemavaults-ui.tgz --gzip-level 9
+      - name: Upload package artifact
+        uses: actions/upload-artifact@v6
+        with:
+          name: package-tarball
+          path: schemavaults-ui.tgz
+          retention-days: 2
+
+  Publish-Package-To-GitHub:
+    name: "Publish @schemavaults/ui to GitHub Packages"
+    runs-on: ubuntu-latest
+    permissions:
+      packages: write
+    needs:
+      - Build
+    steps:
+      - name: Download package artifact
+        uses: actions/download-artifact@v7
+        with:
+          name: package-tarball
+          path: .
+      - name: Assert tarball exists at expected location
+        run: |
+          if [ ! -f schemavaults-ui.tgz ]; then
+            echo "Error: schemavaults-ui.tgz not found!"
+            exit 1
+          fi
       - name: Configure .npmrc to publish to GitHub NPM registry
         run: cp .npmrc.github .npmrc
       - name: Publish package to GitHub NPM registry
@@ -40,12 +67,31 @@ jobs:
           SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Delete .npmrc for GitHub NPM registry
         run: rm -rf .npmrc
-      - name: Configure .npmrc to publish to NPMJS registry
-        run: cp .npmrc.npmjs .npmrc
+
+  Publish-Package-To-Npmjs:
+    name: "Publish @schemavaults/ui to NPMJS registry"
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write # Required for OIDC
+    needs:
+      - Build
+    steps:
+      - uses: actions/setup-node@v5
+        with:
+          node-version: "24"
+          registry-url: "https://registry.npmjs.org"
+      - name: Download package artifact
+        uses: actions/download-artifact@v7
+        with:
+          name: package-tarball
+          path: .
+      - name: Assert tarball exists at expected location
+        run: |
+          if [ ! -f schemavaults-ui.tgz ]; then
+            echo "Error: schemavaults-ui.tgz not found!"
+            exit 1
+          fi
       - name: Publish package to NPMJS registry
-        run: bun publish --registry=https://registry.npmjs.org
-        env:
-          NPM_PACKAGE_PUBLISH_USER: ${{ github.actor }}
-          NPM_PACKAGE_PUBLISH_TOKEN: ${{ secrets.NPM_PACKAGE_PUBLISH_TOKEN }}
+        run: npm publish ./schemavaults-ui.tgz --provenance
       - name: Delete .npmrc for NPMJS registry
         run: rm -rf .npmrc
